### ISSUE TITLE
main.py can read 8 bit grey picture and report error while train dataset horse2zebra

### ISSUE THREAD

**Issue by taichu012** [hardikbansal/CycleGAN#4]
While in source code main.py， below line can't procedure gray picture（8 bit color deep） in horse2zebra dataset(after unzip horse2zebra dataset, I find some picture is gray with 8 bit deep in trainB), and get err.

self.B_input[i] = image_tensor.reshape((batch_size,img_height, img_width, img_layer))
ValueError: cannot reshape array of size 65536 into shape (1,256,256,3)

**Comment by taichu012** [comment]
One workaround way is to remove all gray picture in horse2zebra\trainB hasing 8 bits color depth manually. But its better to let main.py can do it self by some better way. thanks

**Comment by hardikbansal** [comment]
Yeah, you are correct. There are some grey scale images. We manually removed those images (couple of commands). I will correct the code and update the  issue. Thanks for your input.

**Comment by hardikbansal** [comment]
Corrected the code. Closing the issue.
