### ISSUE TITLE
placeholder input_a and real pic variable a_input have different width and height if input pic dataset is not square

### ISSUE THREAD

**Issue by taichu012** [hardikbansal/CycleGAN#7]
From my opinion, paired model pix2pix is special case of unpaired model cyclegan, so i try to use labeled fake pic and real camera pic as input A AND B to train incyclegan model. both size of them are 96wx32h(not square w==h), then i find main.py cannot run and report reshape error(you can use no-square pic  and train model then maybe get the error).after some guess and detail look on your codes, it seems input_A's width set to height of the A_input. But it can also run if train data and test data are both square.  anyhow,    after adjusted(swtich) position of w and h, i run the model trained and tested, also the final result is not as better as i image, maybe i need adjust lr or other Hparams. 

thanks so much for provide tensorflow version of cyclegan.

finally, sorry for my poor English.

**Comment by hardikbansal** [comment]
Yeah. Maybe parameter adjusting is required. I will change the code to support the dimensions of non-square images
